export const CANDIDATE_SEEDS = [
  {
    firstName: 'Anjali', lastName: 'Verma',
    email: 'anjali.verma@vetmail.test', phone: '9810000001',
    address: '14 Linking Road, Bandra West', city: 'Mumbai', pincode: '400050',
    currentLocation: 'Mumbai', gender: 'Female', aadhaarVerified: true,
    preferredLocations: ['Mumbai', 'Pune', 'Bangalore'],
    profileSummary: 'Small-animal surgeon with 6 years of experience in soft-tissue and orthopedic surgery for canines and felines.',
    photoUrl: '', degree: 'BVSc', educationLevel: 'Graduate',
    specialization: 'Small Animal Surgery', courseType: 'Full-time',
    courseStartDate: '2014-07-01', courseEndDate: '2019-06-30', grade: 'A',
    educationCountry: 'India', educationCity: 'Mumbai',
    additionalDetails: 'Trained at Bombay Veterinary College.',
    certifications: ['Pet First Aid', 'Advanced Surgical Techniques'],
    professionalLicenses: 'VCI Reg. No. 12345/MH',
    currentJobTitle: 'Senior Veterinary Surgeon', employmentType: 'Full-time',
    organizationName: 'PetCare Multi-Specialty Hospital',
    currentSalary: '900000', salaryFormat: 'per annum',
    skills: ['Surgery', 'Diagnostics', 'Emergency Care', 'Pet Care'],
    experiences: [
      { jobTitle: 'Senior Veterinary Surgeon', employmentType: 'Full-time', organizationName: 'PetCare Multi-Specialty Hospital', joiningDate: '2022-04-01', endDate: '', roleDescription: 'Lead surgeon for orthopedic and soft-tissue procedures.' },
      { jobTitle: 'Associate Veterinarian', employmentType: 'Full-time', organizationName: 'Bandra Pet Clinic', joiningDate: '2019-08-01', endDate: '2022-03-31', roleDescription: 'Outpatient consultations, vaccinations, and minor surgery.' },
    ],
    status: 'submitted',
  },
  {
    firstName: 'Rakesh', lastName: 'Patil',
    email: 'rakesh.patil@vetmail.test', phone: '9810000002',
    address: 'Plot 22, Baner Road', city: 'Pune', pincode: '411045',
    currentLocation: 'Pune', gender: 'Male', aadhaarVerified: true,
    preferredLocations: ['Pune', 'Nashik', 'Kolhapur'],
    profileSummary: 'Livestock and large-animal veterinarian focused on dairy herd health and productivity.',
    photoUrl: '', degree: 'BVSc', educationLevel: 'Graduate',
    specialization: 'Large Animal Medicine', courseType: 'Full-time',
    courseStartDate: '2010-07-01', courseEndDate: '2015-06-30', grade: 'A',
    educationCountry: 'India', educationCity: 'Pune',
    certifications: ['Dairy Herd Management'],
    professionalLicenses: 'VCI Reg. No. 22045/MH',
    currentJobTitle: 'Lead Livestock Veterinarian', employmentType: 'Full-time',
    organizationName: 'GreenField Dairy Farms',
    currentSalary: '750000', salaryFormat: 'per annum',
    skills: ['Large Animals', 'Vaccination', 'Diagnostics', 'Nutrition'],
    experiences: [
      { jobTitle: 'Lead Livestock Veterinarian', employmentType: 'Full-time', organizationName: 'GreenField Dairy Farms', joiningDate: '2020-01-15', endDate: '', roleDescription: 'Herd health management for 1200+ cattle.' },
    ],
    status: 'submitted',
  },
  {
    firstName: 'Priya', lastName: 'Reddy',
    email: 'priya.reddy@vetmail.test', phone: '9810000003',
    address: '7-1-22 Begumpet', city: 'Hyderabad', pincode: '500016',
    currentLocation: 'Hyderabad', gender: 'Female', aadhaarVerified: true,
    preferredLocations: ['Hyderabad', 'Bangalore'],
    profileSummary: 'Avian and exotic-species clinician with focus on parrots, raptors, and small mammals.',
    photoUrl: '', degree: 'MVSc', educationLevel: 'Postgraduate',
    specialization: 'Avian Medicine', courseType: 'Full-time',
    courseStartDate: '2017-07-01', courseEndDate: '2019-06-30', grade: 'A+',
    educationCountry: 'India', educationCity: 'Hyderabad',
    certifications: ['Avian Anesthesia', 'Exotic Pet Care'],
    professionalLicenses: 'VCI Reg. No. 33012/TS',
    currentJobTitle: 'Avian Specialist', employmentType: 'Full-time',
    organizationName: 'Exotic Wings Veterinary Center',
    currentSalary: '820000', salaryFormat: 'per annum',
    skills: ['Avian', 'Diagnostics', 'Surgery', 'Pet Care'],
    experiences: [
      { jobTitle: 'Avian Specialist', employmentType: 'Full-time', organizationName: 'Exotic Wings Veterinary Center', joiningDate: '2021-06-01', endDate: '', roleDescription: 'Clinical care for exotic birds and reptiles.' },
    ],
    status: 'submitted',
  },
  {
    firstName: 'Vikram', lastName: 'Singh',
    email: 'vikram.singh@vetmail.test', phone: '9810000004',
    address: 'B-204, Sector 18', city: 'Noida', pincode: '201301',
    currentLocation: 'Delhi NCR', gender: 'Male', aadhaarVerified: true,
    preferredLocations: ['Delhi NCR', 'Gurgaon'],
    profileSummary: '24x7 emergency and critical-care veterinarian with ICU and trauma management experience.',
    photoUrl: '', degree: 'BVSc', educationLevel: 'Graduate',
    specialization: 'Emergency & Critical Care', courseType: 'Full-time',
    courseStartDate: '2013-07-01', courseEndDate: '2018-06-30', grade: 'A',
    educationCountry: 'India', educationCity: 'Delhi',
    certifications: ['Veterinary CPR', 'Emergency Medicine'],
    professionalLicenses: 'VCI Reg. No. 41098/DL',
    currentJobTitle: 'Emergency Veterinarian', employmentType: 'Full-time',
    organizationName: 'CityVet 24x7 Emergency Hospital',
    currentSalary: '950000', salaryFormat: 'per annum',
    skills: ['Emergency Care', 'Surgery', 'Diagnostics', 'Pet Care'],
    experiences: [
      { jobTitle: 'Emergency Veterinarian', employmentType: 'Full-time', organizationName: 'CityVet 24x7 Emergency Hospital', joiningDate: '2020-09-01', endDate: '', roleDescription: 'Triage, ICU monitoring, and emergency surgery.' },
    ],
    status: 'submitted',
  },
  {
    firstName: 'Meena', lastName: 'Iyer',
    email: 'meena.iyer@vetmail.test', phone: '9810000005',
    address: '12 T Nagar', city: 'Chennai', pincode: '600017',
    currentLocation: 'Chennai', gender: 'Female', aadhaarVerified: true,
    preferredLocations: ['Chennai', 'Coimbatore'],
    profileSummary: 'Veterinary pathologist specialized in histopathology and infectious-disease diagnostics.',
    photoUrl: '', degree: 'PhD', educationLevel: 'Doctorate',
    specialization: 'Veterinary Pathology', courseType: 'Full-time',
    courseStartDate: '2015-08-01', courseEndDate: '2019-12-15', grade: 'Distinction',
    educationCountry: 'India', educationCity: 'Chennai',
    certifications: ['Histopathology', 'PCR Diagnostics'],
    professionalLicenses: 'VCI Reg. No. 50087/TN',
    currentJobTitle: 'Senior Pathologist', employmentType: 'Full-time',
    organizationName: 'AnimalLab Diagnostics',
    currentSalary: '1100000', salaryFormat: 'per annum',
    skills: ['Diagnostics', 'Pet Care'],
    experiences: [
      { jobTitle: 'Senior Pathologist', employmentType: 'Full-time', organizationName: 'AnimalLab Diagnostics', joiningDate: '2020-02-01', endDate: '', roleDescription: 'Histopathology, biopsy reads, and infectious-disease panels.' },
    ],
    status: 'submitted',
  },
  {
    firstName: 'Suresh', lastName: 'Choudhary',
    email: 'suresh.choudhary@vetmail.test', phone: '9810000006',
    address: 'Village Mansagar, Tonk Road', city: 'Jaipur', pincode: '302015',
    currentLocation: 'Jaipur', gender: 'Male', aadhaarVerified: true,
    preferredLocations: ['Jaipur', 'Jodhpur', 'Udaipur'],
    profileSummary: 'Cattle and buffalo specialist with field expertise in dairy productivity and breeding programs.',
    photoUrl: '', degree: 'BVSc', educationLevel: 'Graduate',
    specialization: 'Dairy & Cattle Medicine', courseType: 'Full-time',
    courseStartDate: '2008-07-01', courseEndDate: '2013-06-30', grade: 'B+',
    educationCountry: 'India', educationCity: 'Bikaner',
    certifications: ['Bovine AI Technician', 'Mastitis Management'],
    professionalLicenses: 'VCI Reg. No. 60234/RJ',
    currentJobTitle: 'District Veterinary Officer', employmentType: 'Full-time',
    organizationName: 'Rajasthan Livestock Development Board',
    currentSalary: '650000', salaryFormat: 'per annum',
    skills: ['Large Animals', 'Vaccination', 'Diagnostics'],
    experiences: [
      { jobTitle: 'District Veterinary Officer', employmentType: 'Full-time', organizationName: 'Rajasthan Livestock Development Board', joiningDate: '2018-01-01', endDate: '', roleDescription: 'Coordinate cattle health camps and vaccination drives across 80+ villages.' },
    ],
    status: 'submitted',
  },
  {
    firstName: 'Neha', lastName: 'Gupta',
    email: 'neha.gupta@vetmail.test', phone: '9810000007',
    address: '305 Indiranagar 100ft Road', city: 'Bangalore', pincode: '560038',
    currentLocation: 'Bangalore', gender: 'Female', aadhaarVerified: true,
    preferredLocations: ['Bangalore', 'Chennai', 'Mumbai'],
    profileSummary: 'Pet nutrition consultant designing custom diet plans for canines, felines, and small mammals.',
    photoUrl: '', degree: 'MVSc', educationLevel: 'Postgraduate',
    specialization: 'Animal Nutrition', courseType: 'Full-time',
    courseStartDate: '2016-08-01', courseEndDate: '2018-07-30', grade: 'A',
    educationCountry: 'India', educationCity: 'Bangalore',
    certifications: ['Companion Animal Nutrition', 'Clinical Dietetics'],
    professionalLicenses: 'VCI Reg. No. 70566/KA',
    currentJobTitle: 'Pet Nutrition Consultant', employmentType: 'Full-time',
    organizationName: 'Whiskers & Tails Wellness',
    currentSalary: '720000', salaryFormat: 'per annum',
    skills: ['Nutrition', 'Pet Care', 'Diagnostics'],
    experiences: [
      { jobTitle: 'Pet Nutrition Consultant', employmentType: 'Full-time', organizationName: 'Whiskers & Tails Wellness', joiningDate: '2021-03-01', endDate: '', roleDescription: 'Custom diet plans, weight-loss programs, and nutritional counseling.' },
    ],
    status: 'submitted',
  },
  {
    firstName: 'Arjun', lastName: 'Nair',
    email: 'arjun.nair@vetmail.test', phone: '9810000008',
    address: 'Marine Drive, Ernakulam', city: 'Kochi', pincode: '682031',
    currentLocation: 'Kochi', gender: 'Male', aadhaarVerified: true,
    preferredLocations: ['Kochi', 'Bangalore', 'Mumbai'],
    profileSummary: 'Wildlife veterinarian with field experience in elephant, tiger, and marine-mammal care.',
    photoUrl: '', degree: 'MVSc', educationLevel: 'Postgraduate',
    specialization: 'Wildlife Medicine', courseType: 'Full-time',
    courseStartDate: '2014-08-01', courseEndDate: '2016-07-30', grade: 'A',
    educationCountry: 'India', educationCity: 'Thrissur',
    certifications: ['Wildlife Anesthesia', 'Field Immobilization'],
    professionalLicenses: 'VCI Reg. No. 80123/KL',
    currentJobTitle: 'Wildlife Veterinarian', employmentType: 'Full-time',
    organizationName: 'Kerala Forest & Wildlife Department',
    currentSalary: '880000', salaryFormat: 'per annum',
    skills: ['Surgery', 'Emergency Care', 'Diagnostics', 'Large Animals'],
    experiences: [
      { jobTitle: 'Wildlife Veterinarian', employmentType: 'Full-time', organizationName: 'Kerala Forest & Wildlife Department', joiningDate: '2019-05-01', endDate: '', roleDescription: 'Wildlife rescue, rehabilitation, and zoo medicine.' },
    ],
    status: 'submitted',
  },
  {
    firstName: 'Pooja', lastName: 'Joshi',
    email: 'pooja.joshi@vetmail.test', phone: '9810000009',
    address: 'B-12 Satellite Road', city: 'Ahmedabad', pincode: '380015',
    currentLocation: 'Ahmedabad', gender: 'Female', aadhaarVerified: true,
    preferredLocations: ['Ahmedabad', 'Surat', 'Gujarat'],
    profileSummary: 'Veterinary reproduction and AI specialist focused on cattle and buffalo breeding programs.',
    photoUrl: '', degree: 'MVSc', educationLevel: 'Postgraduate',
    specialization: 'Animal Reproduction', courseType: 'Full-time',
    courseStartDate: '2015-08-01', courseEndDate: '2017-07-30', grade: 'A',
    educationCountry: 'India', educationCity: 'Anand',
    certifications: ['Bovine AI', 'Embryo Transfer'],
    professionalLicenses: 'VCI Reg. No. 90442/GJ',
    currentJobTitle: 'AI & Reproduction Specialist', employmentType: 'Full-time',
    organizationName: 'Amul Cooperative Veterinary Services',
    currentSalary: '780000', salaryFormat: 'per annum',
    skills: ['Large Animals', 'Diagnostics', 'Vaccination'],
    experiences: [
      { jobTitle: 'AI & Reproduction Specialist', employmentType: 'Full-time', organizationName: 'Amul Cooperative Veterinary Services', joiningDate: '2019-09-01', endDate: '', roleDescription: 'Artificial insemination, pregnancy diagnosis, and reproductive health.' },
    ],
    status: 'submitted',
  },
  {
    firstName: 'Karan', lastName: 'Malhotra',
    email: 'karan.malhotra@vetmail.test', phone: '9810000010',
    address: 'DLF Phase 4, Sector 28', city: 'Gurgaon', pincode: '122009',
    currentLocation: 'Gurgaon', gender: 'Male', aadhaarVerified: true,
    preferredLocations: ['Gurgaon', 'Delhi NCR', 'Noida'],
    profileSummary: 'Veterinary radiologist with expertise in MRI, CT, and ultrasound diagnostics for companion animals.',
    photoUrl: '', degree: 'MVSc', educationLevel: 'Postgraduate',
    specialization: 'Veterinary Radiology', courseType: 'Full-time',
    courseStartDate: '2016-08-01', courseEndDate: '2018-07-30', grade: 'A+',
    educationCountry: 'India', educationCity: 'Hisar',
    certifications: ['Diagnostic Imaging', 'Ultrasonography'],
    professionalLicenses: 'VCI Reg. No. 99876/HR',
    currentJobTitle: 'Veterinary Radiologist', employmentType: 'Full-time',
    organizationName: 'MaxVet Imaging Center',
    currentSalary: '1050000', salaryFormat: 'per annum',
    skills: ['Diagnostics', 'Surgery', 'Emergency Care', 'Pet Care'],
    experiences: [
      { jobTitle: 'Veterinary Radiologist', employmentType: 'Full-time', organizationName: 'MaxVet Imaging Center', joiningDate: '2020-11-01', endDate: '', roleDescription: 'Cross-sectional imaging, ultrasonography, and report consultations.' },
    ],
    status: 'submitted',
  },
];
