const API_VERSION = '/api/v1';

export const API_ENDPOINTS = {
  auth: {
    sendOtp: `${API_VERSION}/auth/send-otp`,
    verifyOtp: `${API_VERSION}/auth/verify-otp`,
    switchProfile: `${API_VERSION}/auth/switch-profile`,
  },
  candidateProfiles: `${API_VERSION}/candidate-profiles`,
  candidateProfileMe: `${API_VERSION}/candidate-profiles/me`,
  candidateProfileImage: `${API_VERSION}/candidate-profiles/image`,
  candidateProfilesFeatured: `${API_VERSION}/candidate-profiles/featured`,
  candidateProfileById: (id: string) => `${API_VERSION}/candidate-profiles/${id}`,
  candidateResumeById: (id: string) => `${API_VERSION}/candidate-profiles/${id}/resume`,
  myResume: `${API_VERSION}/candidate-profiles/me/resume`,
  myResumeRefine: `${API_VERSION}/candidate-profiles/me/resume/refine`,
  employerProfiles: `${API_VERSION}/employer-profiles`,
  employerProfileMe: `${API_VERSION}/employer-profiles/me`,
  employerProfileLogo: `${API_VERSION}/employer-profiles/logo`,
  employerProfilePrefill: `${API_VERSION}/employer-profiles/prefill`,
  employerProfileById: (id: string) => `${API_VERSION}/employer-profiles/${id}`,
  jobs: `${API_VERSION}/jobs`,
  myJobs: `${API_VERSION}/jobs/my`,
  jobById: (id: string) => `${API_VERSION}/jobs/${id}`,
  applications: `${API_VERSION}/applications`,
  myApplications: `${API_VERSION}/applications/me`,
  myApplicationStatus: (jobId: string) => `${API_VERSION}/applications/me/job/${jobId}`,
  autoApply: `${API_VERSION}/applications/auto-apply`,
  employerApplications: `${API_VERSION}/applications/employer`,
  employerApplicationById: (id: string) => `${API_VERSION}/applications/employer/${id}`,
  savedJobs: `${API_VERSION}/saved-jobs`,
  mySavedJobs: `${API_VERSION}/saved-jobs/me`,
  savedJobById: (jobId: string) => `${API_VERSION}/saved-jobs/${jobId}`,
  chatConversations: `${API_VERSION}/chat/conversations`,
  chatConversationMessages: (id: string) => `${API_VERSION}/chat/conversations/${id}/messages`,
  chatConversationRead: (id: string) => `${API_VERSION}/chat/conversations/${id}/read`,
  chatUnreadCount: `${API_VERSION}/chat/unread-count`,
  jobTypes: `${API_VERSION}/job-types`,
  jobTypeById: (id: string) => `${API_VERSION}/job-types/${id}`,
  skills: `${API_VERSION}/skills`,
  skillById: (id: string) => `${API_VERSION}/skills/${id}`,
  educations: `${API_VERSION}/educations`,
  educationById: (id: string) => `${API_VERSION}/educations/${id}`,
  salaryUnits: `${API_VERSION}/salary-units`,
  salaryUnitById: (id: string) => `${API_VERSION}/salary-units/${id}`,
  aiRefineCandidateProfile: `${API_VERSION}/ai/candidate-profile/refine`,
  aiJobSearch: `${API_VERSION}/ai/jobs/search`,
  aiJobReindex: `${API_VERSION}/ai/jobs/reindex`,
  plans: `${API_VERSION}/plans`,
  subscriptionMe: `${API_VERSION}/subscriptions/me`,
  subscriptionUsage: `${API_VERSION}/subscriptions/usage`,
  subscriptionCheckout: `${API_VERSION}/subscriptions/checkout`,
  subscriptionConfirm: `${API_VERSION}/subscriptions/confirm`,
  subscriptionCancel: `${API_VERSION}/subscriptions/cancel`,
  purchaseAddons: `${API_VERSION}/purchases/addons`,
  purchaseCheckout: `${API_VERSION}/purchases/checkout`,
  purchaseConfirm: `${API_VERSION}/purchases/confirm`,
  myPurchases: `${API_VERSION}/purchases/me`,
  candidateUnlock: (id: string) => `${API_VERSION}/candidate-profiles/${id}/unlock`,
  verifyPhone: `${API_VERSION}/candidate-profiles/me/verify-phone`,
  verifyPhoneConfirm: `${API_VERSION}/candidate-profiles/me/verify-phone/confirm`,
  myFollows: `${API_VERSION}/candidate-profiles/me/follows`,
  employerFollow: (id: string) => `${API_VERSION}/employer-profiles/${id}/follow`,
} as const;
